// Generated by https://quicktype.io

export interface PokemonAPIResults {
  count: number;
  next: string;
  previous: null;
  results: Pokemons[];
}

export interface Pokemons {
  name: string;
  url: string;
}

export interface Pokemon {
  id: string;
  name: string;
  picture: string;
  color?: string;
}
